### ISSUE TITLE
Configure MAX_UNAUTH_*

### ISSUE THREAD

**Issue by dgutson** [PerezFederico/dropbear#12]
currently:
```c
#define MAX_UNAUTH_PER_IP 2
#define MAX_UNAUTH_CLIENTS 4
```
Check what they are, and whether they can be 0 (DANGER: they are used to dimension arrays, so beware of 0-length arrays, avoid them).

**Comment by 0xfede7c8** [comment]
Already investigated, already overriden.

**Comment by dgutson** [comment]
4 is too much. Set it to minimum  (1?) always thinking in our usecase.
